# Generated by Django 3.2.5 on 2021-07-31 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('course_credits', models.CharField(max_length=50)),
                ('modality', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('prof', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('courses', models.ForeignKey(blank=True, db_column='ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profs', to='course_picker.coursecontent')),
            ],
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('special', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('FOMO', models.CharField(max_length=50)),
                ('professor', models.ForeignKey(blank=True, db_column='prof', null=True, on_delete=django.db.models.deletion.CASCADE, to='course_picker.prof')),
            ],
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='faculty',
            field=models.ForeignKey(blank=True, db_column='prof', null=True, on_delete=django.db.models.deletion.CASCADE, to='course_picker.prof'),
        ),
    ]
