# Generated by Django 3.2.5 on 2021-08-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_picker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='faculty',
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='faculty',
            field=models.ManyToManyField(to='course_picker.Prof'),
        ),
    ]
