# Generated by Django 3.2.5 on 2021-08-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_picker', '0002_auto_20210801_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='professor',
            field=models.ForeignKey(blank=True, db_column='prof', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Speciality', to='course_picker.prof'),
        ),
    ]
