# Generated by Django 3.2.5 on 2021-08-01 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_picker', '0004_alter_spec_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Specialities', to='course_picker.prof'),
        ),
    ]
