# Generated by Django 3.2.5 on 2021-08-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_picker', '0006_alter_spec_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='professor',
        ),
        migrations.AddField(
            model_name='spec',
            name='professor',
            field=models.ManyToManyField(to='course_picker.Prof'),
        ),
    ]
